name = "openlistnextpro"
main = "src/backend/worker.ts"
compatibility_date = "2026-08-04"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false

[vars]
ENVIRONMENT = "production"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin"
VITE_API_URL = "/api"

[[kv_namespaces]]
binding = "OPENLIST_KV"
id = "0e48234248a84d4dbdc5a70e886773ea"




