name = "openlistnextpro"
main = "src/backend/worker.ts"
compatibility_date = "2026-08-04"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin"
VITE_API_URL = "/api"

[[kv_namespaces]]
binding = "OPENLIST_KV"
id = "12345"


